Update task.md
jetbrains-academy/Coroutines-and-channels pull request #11
Opened 2023-12-08 16:07 UTC by stephen-hero

language checked

2023-12-11 13:50 UTC, kochaika requested changes

2023-12-11 13:50 UTC, kochaika commented on Coroutines/Callbacks/task.md
> +However, if you try to load the contributors via the `BACKGROUND` option, you can see that whilethe list is updates,
`whilethe` -- I guess it's a typo

2023-12-11 13:50 UTC, kochaika commented on Coroutines/Callbacks/task.md
> +3. Once the `loadContributorsBackground()` is called, the invokation of  `updateResults()` is moved to the callback, instead of being executed immediately
`invokation` -- should it be `invocation`?

2023-12-12 13:55 UTC, stephen-hero commented on Coroutines/Callbacks/task.md
> +However, if you try to load the contributors via the `BACKGROUND` option, you can see that whilethe list is updates,
right.. should be: "while the list updates,"

2023-12-12 13:59 UTC, stephen-hero commented on Coroutines/Callbacks/task.md
> +3. Once the `loadContributorsBackground()` is called, the invokation of  `updateResults()` is moved to the callback, instead of being executed immediately
Absolutely. " Invocation"

2023-12-12 14:56 UTC, kochaika approved these changes

2023-12-12 14:56 UTC, merged